// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8QZM1JzRfISAsK-v16c-l8p0Noo50x-o',
    appId: '1:415105032586:web:f0490d892fb3c7952fe873',
    messagingSenderId: '415105032586',
    projectId: 'cinema-app-5aef4',
    authDomain: 'cinema-app-5aef4.firebaseapp.com',
    storageBucket: 'cinema-app-5aef4.firebasestorage.app',
    measurementId: 'G-Y4CPHLFW52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19C-tPfKLRjKDT8yfweZKB4xVIt8wawk',
    appId: '1:415105032586:android:796a55ab7804fa442fe873',
    messagingSenderId: '415105032586',
    projectId: 'cinema-app-5aef4',
    storageBucket: 'cinema-app-5aef4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkaTCu3y4Ag0nDKW5DASBrNKpcI28Y-aQ',
    appId: '1:415105032586:ios:93b1caaac9904e5d2fe873',
    messagingSenderId: '415105032586',
    projectId: 'cinema-app-5aef4',
    storageBucket: 'cinema-app-5aef4.firebasestorage.app',
    iosBundleId: 'com.example.cinemaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkaTCu3y4Ag0nDKW5DASBrNKpcI28Y-aQ',
    appId: '1:415105032586:ios:93b1caaac9904e5d2fe873',
    messagingSenderId: '415105032586',
    projectId: 'cinema-app-5aef4',
    storageBucket: 'cinema-app-5aef4.firebasestorage.app',
    iosBundleId: 'com.example.cinemaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8QZM1JzRfISAsK-v16c-l8p0Noo50x-o',
    appId: '1:415105032586:web:de13780d818ae1b92fe873',
    messagingSenderId: '415105032586',
    projectId: 'cinema-app-5aef4',
    authDomain: 'cinema-app-5aef4.firebaseapp.com',
    storageBucket: 'cinema-app-5aef4.firebasestorage.app',
    measurementId: 'G-720M0N0BYC',
  );
}
